version: 2
updates:
  - package-ecosystem: "npm"
    directory: "../"
    schedule:
      interval: "weekly"
      # Check for npm updates on Monday at 9AM ET
      day: "monday"
      time: "14:00"
    assignees:
      - "yeet-bot7800"
    reviewers:
      - "Cyber4All/dev-sec-ops"
    labels:
      - "npm dependencies"
    target-branch: "main"
